on:
    push: ~

jobs:
    big_query:
        name: Big Query
        runs-on: ubuntu-latest
        steps:
            - id: auth
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: '${{ secrets.GCLOUD_BIG_QUERY }}'
      
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: pip install termcolor

            - name: List datasets
              run: bq query 'SELECT * FROM `vlad_test.mockaroo`'
