on:
    push: ~

jobs:
    big_query:
        name: Big Query
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
          
            - name: Install dependencies
              run: pip install termcolor

            - id: auth
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: '${{ secrets.GCLOUD_BIG_QUERY }}'
      
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - name: List datasets
              run: |
                bq query \
                    --quiet \
                    --headless \
                    --format=csv \
                    --use_legacy_sql=false \
                    "SELECT * FROM \`vlad_test.mockaroo\`"
