name: Demo Workflow

on:
    push: ~

jobs:
    tests:
        name: Get Bash Version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get version
              run: echo ${BASH_VERSION}
