name: Demo Workflow

on:
  issues:
    types: [labeled]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'bug' || github.event.label.name == 'invalid'
    steps:
        - run: |
            echo "hello"
